# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toondere', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtoon',
            old_name='href',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='webtoon',
            old_name='thumbnail',
            new_name='thumbnail_big',
        ),
        migrations.AddField(
            model_name='webtoon',
            name='thumbnail_small',
            field=models.TextField(null=True),
        ),
    ]
