# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toondere', '0004_auto_20160803_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeWebtoon',
        ),
    ]
